[tool.poetry]
name = "elt-dbt"
version = "0.1.0"
description = ""
authors = ["GenivaldoSerra <genivaldo.serra@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
